### ISSUE TITLE
firewall

### ISSUE THREAD

**Issue by RREReer** [Lakatrazz/Fusion-Helper#27]
i allowed public and private networks in firewall but it still says this
<img width="960" alt="Desktop Screenshot 2023 09 23 - 19 56 54 17" src="https://github.com/Lakatrazz/Fusion-Helper/assets/145881051/382b6d40-1094-4561-bdda-6ede54afd86a">

**Comment by sasdallas** [comment]
Double check your quest is connected to the same internet and the mods are in the right place.
Bonelib, Fusion, and RagdollPlayer need to be in Mods, and LemonLoader needs to be installed.

**Comment by EthanRomine** [comment]
This fixed it for me:

1. Go into your router settings
2. Go into your basic Internet settings
3. Make sure that you have both DNS and IP address set to "get Automatically/Dynamically from ISP"

It won't be exactly like above because we all have a different router model but as long as you change the DNS and IP setting to what's above it should fix it. This also might not be the reason for everyone.

**Comment by Lakatrazz** [comment]
Stale
